language: python
python:
  - 2.7
env:
  - PLONE=4.2
  - PLONE=4.3
before_install:
  - pip install http://effbot.org/downloads/Imaging-1.1.6.tar.gz
  - sudo apt-get install -qq libxml2-dev libxslt-dev
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
install:
  - python bootstrap.py -c -d travis-$PLONE.cfg
  - bin/buildout -t 5 -Nqc travis-$PLONE.cfg
script:
  - bin/test